### ISSUE TITLE
Consumer stucks in reconnections

### ISSUE THREAD

**Issue by myromeu** [wyyerd/pulsar-rs#263]
Hello everyone.

Want to report a bug.

### Versions:
pulsar-rs = 4.2.0 (also reproduced on 5.1.0)
apache pulsar = 2.9.2

### Relates:
https://github.com/streamnative/pulsar-rs/issues/189

### Attachments:
- Cargo.toml: https://gist.github.com/myromeu/c4d5ea48b2b2c5b989fea36665ea2508#file-cargo-toml
- main.rs: https://gist.github.com/myromeu/c4d5ea48b2b2c5b989fea36665ea2508#file-main-rs
- 4.2.0.log: https://gist.github.com/myromeu/c4d5ea48b2b2c5b989fea36665ea2508#file-4-2-0-log
- 5.1.0.log: https://gist.github.com/myromeu/c4d5ea48b2b2c5b989fea36665ea2508#file-5-1-0-log

### To reproduce:
- Start consumer and producer on topic (persistent or not doesn't matter) with env RUST_LOG=pulsar=debug.
- Make unload namespace with command: `bin/pulsar-admin namespaces unload foo/bar`. But sometimes it reproduces in another unclear circumstances(:
- After this consumer stucks in infinitely in reconnections (look attached files for logs).

### Own findings:
In ConsumerEngine after registering sources it iterates them and sends to the engine. And in main loop inside `ConsumerEngine::engine` while looping it tries to reconnect if encountered some problems with underlying connection. And when it got `None` from messages source it tries to reconnect. But while it's reconnecting it still receives `None`'s inside registered source's task. After it reconnected it goes back to the main loop and receives collected `None`'s which was collected previously. So after received `None` it should reconnect again. And engine stucks inside this loop: Got None -> Go to reconnect -> Reconnection done -> Got `None` again -> ...

I had solved this with set flag self.reconnected and skip messages with None in the main loop. After skipping None's it resets the flag. But it can skip None message which comes right after reconnection and signals about real disconnection. So it cannot be solution.

**Comment by klaatu01** [comment]
I am currently investigating a similar issue, only mine hangs on the `Retry -> reconnecting consumer 6060164082020851399 using connection 8b4c6c4f-c3fe-4a9a-9252-999cf227a391 to broker pulsar://127.0.0.1:6650 to topic persistent://foo/bar/test-topic` part.

Will see if I come across anything that might cause your issue.

**Comment by myromeu** [comment]
@klaatu01 hello!
It can be caused by forcing ConsumerEngine to reconnect to broker. I'm trying to work on it now. But I can't realize how it receives None when reconnection occure inside ConsumerEngine::register_source's task.

**Comment by NiuBlibing** [comment]
Encounterd the same problem when reseting the consumer's subscription.

**Comment by myromeu** [comment]
@NiuBlibing how you make reset subscription?

**Comment by NiuBlibing** [comment]
use pulsar-manager:
![image](https://user-images.githubusercontent.com/88433283/225581617-043a67a4-e78c-4a1c-8c0a-2b23c3381bad.png)

**Comment by myromeu** [comment]
Hello everyone.

And finaly I found it!

When ConsumerEngine reconnects it makes subscription and sends request:
https://github.com/streamnative/pulsar-rs/blob/master/src/consumer/engine.rs#L725
Which leads to update self.consumers inside Receiver:
https://github.com/streamnative/pulsar-rs/blob/master/src/connection.rs#L158
And previous resolver drops so messages_rx receives None and sends it to ConsumerEngine:
https://github.com/streamnative/pulsar-rs/blob/master/src/consumer/engine.rs#L110
The None signals to ConsumerEngine reconnect again and it loops.

It goes on endlessly.

 @Geal any suggestions how to handle it?

I can make PR which adds flag to ConsumerEngine which will be set after reconnection and will be dropped after it receives None inside ConsumerEngine::handle_message_opt.

**Comment by KannarFr** [comment]
@myromeu Wow nice catch.

**Comment by Wonshtrum** [comment]
I think I solved it. I will try to explain what I understand is happening.
As it involves a lot of parts I will start with a "high level" view of the entire client. It will help to understand the rest and hopefully serve as "documentation" if anything else related to connection/reconnection breaks again.
First, there is `Pulsar`:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/client.rs#L156-L171
that holds a `ConnectionManager`:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection_manager.rs#L111-L120
that holds a `HashMap` that links `BrokerAddress` to `Connection` (I'm skipping some layers here):
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection.rs#L711-L715
Fast forward a bit, in `Connection::new`, `Connection::prepare_stream` is called
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection.rs#L774
which creates a `tokio::net::TcpStream`:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection.rs#L866
and calls `Connection::connect` with it:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection.rs#L883-L890
which, among other things, passes the reading half of the socket to a `Receiver` and continuously polls it:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection.rs#L1014-L1024
the reading half of the socket is stored in `inbound`:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection.rs#L91-L102
Note that `Receiver` also holds a `BTreeMap` linking a consumer_id to a channel producer (it will be very important later).
Polling `Receiver` causes `Receiver::poll` to be called regularly (whenever the socket receives a new packet, among other things):
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection.rs#L133
`inbound` is polled here:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection.rs#L172
as well as a channel receiver called `subscriptions` (which will be important later):
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection.rs#L143
what's important to remember is that `Pulsar` holds a `ConnectionManager` which has a `HashMap` of `Connection` which each started a thread that polls a `Receiver` that holds a `TcpStream`, a `subscriptions` channel receiver and a `BTreeMap` of channel producers (in `consumers`).

On the other hand, there is a `TopicConsumer`
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/topic.rs#L32-L43
The goal of a `TopicConsumer` is to somehow create a link between itself and a `Connection` and forward all messages that are destined to its consumer_id.
In `TopicConsummer::new`:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/topic.rs#L47-L67
a new `mpsc` pair is created `(resolver, messages)`, and a `Connection` to the broker is retrieved with `client.manager.get_connection` (if the `ConnectionManager` already has a valid `Connection` to this `BrokerAddress` it is retrieved from its `HashMap`, otherwise it is first created and stored in the `HashMap`).

The link is establish through the `subscribe` call:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/topic.rs#L73-L84
two distinct things to notice:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection.rs#L476-L510

- the channel producer `resolver` is sent on the `Connection` `registrations` channel in a `Register::Consumer` message.
- a subscribe message is sent on the reading half of the `TcpStream` of the `Connection` (believe me this is what `send_message` is doing)

So there are two distinct effects:

- an internal effect that we will explore just after
- an external effect as the Pulsar server is notified of the new consumer

The `Register::Consumer` is caught by the `Receiver` `registrations` channel:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection.rs#L154-L159
and the `resolver` (the `TopicConsumer` channel producer) is stored in its `consumers` `BTreeMap`.
If `subscribe` is successful, `send_flow` is called:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/topic.rs#L192-L194
that might seem of no importance, but this sends a "Flow" message to the Pulsar server which (in combination with the "Subscribe" message) signals the server to forward the messages addressed to the consumer_id (the "Subscribe" message is not enough!).
Fast forward a bit, the `TopicConsumer` creates a `ConsumerEngine` that holds the channel consumer `messages`:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/engine.rs#L31-L51
and sends it on a thread that continuously polls the `ConsumerEngine::engine`:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/topic.rs#L241-L267
`ConsumerEngine::engine` is a loop. On its first iteration this branch will trigger (as `messages` contains the consumer of the channel `TopicConsumer` just created):
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/engine.rs#L134-L139
`register_source` creates a new thread that, given a channel consumer, relays every message onto the internal `event` channel.
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/engine.rs#L96-L116
in case the channel receives a `None`, it is relayed on `event` and the thread terminates (this will be important later).
Now that a source is registered the loop tries to read from the `event` channel:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/engine.rs#L166-L173
the only branch that is interesting for us is the `EngineEvent::Message`. It corresponds to messages received from the `messages` channel receiver. Those are passed to `handle_message_opt` and it is enough to know for the moment.

So, to sum it all up, how does a `TopicConsumer` relay Pulsar messages?
When the Pulsar server has a message for a consumer_id it relays it to the connection that subscribed (and activate flow) for this id. When the message arrives on the `TcpStream`, the corresponding `Receiver` is polled, the message is pattern matched and falls into this arm:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection.rs#L199-L204
which simply forwards the message to the `resolver` corresponding to this consumer_id. The message is received on the source thread of the corresponding `ConsumerEngine`, and relayed on the `event` channel, which finally calls `handle_message_opt` with it. Without going into too much details, message goes through `process_message`, then `process_payload` (which mainly handles decompression), and finally `send_to_consumer` which adds the message(s) to the output stream of `TopicConsumer`.

Now that we know how it works when it... works. Let's see what happens when a topic is unloaded.
It begins with the Pulsar server that sends a "CloseConsumer" message to all connections that had an active consumer for this topic. When the message arrives on the `TcpStream`, the corresponding `Receiver` is polled, the message is pattern matched and falls into this arm:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/connection.rs#L205-L227
We consider that the request_id is not pending, so we get the `resolver` from the `consumers` like before and send the message on it. Like before the message is received on the source thread of the corresponding `ConsumerEngine`, and relayed on the `event` channel, which calls `handle_message_opt` and then `process_message` with it. The message falls into this arm:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/engine.rs#L352-L367
which calls `ConsumerEngine::reconnect`. First, the address of the new broker for our topic is found with a lookup, then a connection to this broker is fetched:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/engine.rs#L702-L703
Like when we first connected, a `mpsc` pair `(resolver, messages)` is created and the `resolver` is `subscribed` into `connection`.
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/engine.rs#L718
Two possible outcomes:

- if the connection changed the resolver is stored in the `BTreeMap` `consumers` of the corresponding `Receiver`
- if the connection is the same, `resolver` overrides the old `resolver` in the `Receiver` `consumers`

then the new `messages` channel consumer is set and the function returns. On the next loop of `ConsumerEngine::engine`, the new source is registered in a new thread (as `self.messages` is not `None`). At that point, the reconnection should be fully done.

Two problems to notice:
- a "Subscribe" request was sent to the Pulsar server but not a "Flow" request, so the Pulsar server will not forward any messages to this consumer from now on
- what happens to the old source on its thread?

The first issue is easy to fix, we just have to call `send_flow` like here:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/topic.rs#L192-L194
The better thing to do would probably be to merge this code as connection and reconnection are duplicated and this would have prevented this mistake.

The second is more convoluted. I am only sure of what happens if the connection after reconnection is the same (meaning the broker didn't change and we keep the same `Receiver`). It is the case when you test locally, it would be different on a true cluster.
In the case the connection didn't change, the new `resolver` took the place of the old one in the `consumers` `BTreeMap` of the `Receiver`. The old `resolver` drops and as it was the only producer of the channel, a `None` is automatically sent to notify the consumer. The consumer of this channel is the old source of the `ConsumerEngine` which, upon receiving this `None` terminates (@myromeu already found this) and sends a `None` on the `event` channel. This `None` is passed to `handle_message_opt` which decides to reconnect again, looping indefinitely. It is important to understand why: `handle_message_opt` is notified that the `ConsumerEngine` message source died, but it failed to realize it was the old message source, a new one already replaced it.

In case the connection changes, the new `resolver` is stored in another `Receiver` `BTreeMap`, so the old `resolver` is not dropped. So `ConsumerEngine` ends up with two sources on two separate threads, but only the new one will ever send messages, the old one is dead as the old `Receiver` will never get messages for this consumer_id again. I'm not sure of this case, maybe this code is supposed to get rid of the old `resolver` and source:
https://github.com/streamnative/pulsar-rs/blob/bcfa020fe24fb180af508f55fa0f1be4f6bf2c7b/src/consumer/engine.rs#L759-L769
but I don't think it works as intended.

In the end, how to fix this? The simple ways are:

- to not reconnect when `event` receives `None`
- to not send `None` on `event` when the source's `resolver` is dropped

Combined with the `send_flow` this fixes the issue: after a topic unloads the `TopicConsumer` reconnects itself to the broker and receives the following messages. But, are we introducing more bugs? The main question is: do we have other cases where the source's `resolver` is dropped and wants to reconnect? If the only way for a `resolver` to be dropped is through a reconnection (when replaced by a newer `resolver`) then we can safely say that we do not want to reconnect when a `resolver` is dropped. Finally, the case of reconnection on a different broker and what happens to the old `resolver` should also be investigated.

I will propose a PR fixing everything after a bit more testing.

**Comment by tisonkun** [comment]
Fixed released at 5.1.1 - https://crates.io/crates/pulsar/5.1.1

@myromeu maybe you can bump the version and test it out.
